# Portainer template for Modded Minecraft server
version: '3.8'

services:
  mc-paper:
    image: itzg/minecraft-server:java17
    environment:
      TZ: "Europe/Rome"
      VERSION: {{ VERSION }}
      EULA: "TRUE"
      TYPE: {{ TYPE }}
      INIT_MEMORY: "512M"
      MAX_MEMORY: "2G"
      OVERRIDE_SERVER_PROPERTIES: "true"
      #ENABLE_RCON: "false"
      QUERY_PORT: {{ PORT }}
      GAMEMODE: {{ GAMEMODE }}
      DIFFICULTY: {{ DIFFICULTY }}
      SERVER_NAME: {{ SERVER_NAME }}
      SERVER_PORT: {{ PORT }}
      VIEW_DISTANCE: 22
      ENABLE_WHITELIST: "true"
      WHITELIST: "2968e76c-60e6-4c96-b92d-5a7e1229b510"
      OPS: "2968e76c-60e6-4c96-b92d-5a7e1229b510"
    ports:
      - {{ PORT }}:{{ PORT }}/tcp
      - {{ PORT }}:{{ PORT }}/udp
    volumes:
      - minecraft-data:/data

    stdin_open: true
    tty: true

    deploy:
      mode: replicated
      replicas: 0
      placement:
        constraints: 
          - {{NODE_PLACEMENT}}

volumes:
  minecraft-data:
    name: {{ MINECRAFT_VOLUME }}